[package]
name = "smol-concurrency-tools"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "testing"
path = "src/bin.rs"

[dependencies]
futures-concurrency = "7"
paste = { version = "1", optional = true }
smol = "2"

[features]
# default = ["select"]
select = ["dep:paste"]
